config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'foods#index'

  get '/recipes', to: 'recipes#index'
  get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  post 'recipes', to: 'recipes#create', as: 'create_recipe'
  get '/recipes/:recipe_id', to: 'recipes#show', as: 'show_recipe'

  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  post '/foods', to: 'foods#create', as: 'create_food'
  delete 'foods/:food_id', to: 'foods#destroy', as: 'destroy_food'

  get '/recipes/:recipe_id/recipe_foods/new', to: 'recipe_foods#new', as: 'new_recipe_food'
  post '/recipe_foods', to: 'recipe_foods#create', as: 'create_recipe_food'
  get '/recipes/:recipe_id/recipe_foods/edit/:recipe_food_id', to: 'recipe_foods#edit', as: 'edit_recipe_food'
  patch '/recipe_foods', to: 'recipe_foods#update', as: 'update_recipe_food'

  delete 'recipes/:recipe_id', to: 'recipes#destroy', as: 'destroy_recipe'
  delete 'recipe_foods/:recipe_foods_id', to: 'recipe_foods#destroy', as: 'destroy_recipe_food'

  get '/public_recipes', to: 'public_recipes#index'
  get '/shopping_list', to: 'shopping_list#index'
end

app/controllers/foods_controller.rb
require 'pry'

class FoodsController < ApplicationController
  def index
    @current_user = current_user
    @foods = Food.where(user: current_user)
  end

  def new
    @current_user = current_user
    @food = Food.new
    @units = %w[grams units kilograms litre]
  end

  def create
    @food = Food.new(foods_params)
    @food.user = current_user
    if @food.save
      flash[:success] = 'Food created successfully'
    else
      flash.now[:error] = 'Error: Food could not be saved'
    end
    redirect_to '/foods'
  end

  def destroy
    @food = Food.find(params[:food_id])
    @food.destroy
    redirect_to(request.referer)
  rescue StandardError
    flash[:message] = 'Cannot delete, it belongs to a recipe.'
    redirect_to(request.referer)
  end

  private

  def foods_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/recipe_foods_controller.rb
require 'pry'

class RecipeFoodsController < ApplicationController
  def new
    @current_user = current_user
    @recipe_food = RecipeFood.new
    @foods = Food.where(user: current_user)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @foods = Food.where(user: current_user)
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe

    if @recipe_food.save
      flash[:notice] = 'Recipe Food saved successfully'
    else
      flash[:alert] = 'Recipe Food not saved'
    end
    redirect_to recipes_path
  end

  def edit
    p params
    @recipe_food = RecipeFood.find(params[:recipe_food_id])
    @foods = Food.where(user: current_user)
  end

  def update
    @recipe_food.quantity = recipe_food_params[:quantity]

    if @recipe_food.update(recipe_food_params)
      flash[:notice] = 'Recipe Food updated successfully'
    else
      flash[:alert] = 'Recipe Food not updated'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    p params
    @current_user = current_user
    recipe_food = RecipeFood.find(params[:recipe_foods_id])
    recipe_food.destroy
    redirect_to(request.referer)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
require 'pry'

class RecipesController < ApplicationController
  def index
    @current_user = current_user
    @recipes = Recipe.where(user: current_user)
  end

  def new
    # p params
    # binding.pry
    @current_user = current_user
    @recipe = Recipe.new
    @foods = Food.where(user: current_user)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:notice] = 'Recipe saved successfully'
    else
      flash[:alert] = 'Recipe not saved'
    end
    redirect_to recipes_path
  end

  def show
    @current_user = current_user
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_foods = RecipeFood.where(recipe_id: params[:recipe_id])
    @foods = Food.where(user: current_user)
  end

  # <%if food.id == recipe_food.food_id%>
  #   <%=food.name%>
  # <%end%>

  def destroy
    @current_user = current_user
    recipe = Recipe.find(params[:recipe_id])
    recipe.destroy
    redirect_to(request.referer)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :cooking_time, :preparation_time, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/foods/_food.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.price %></td>
  <td><%= food.quantity %></td>
  <td >
    <ul class="d-sm-flex">
      <li><%= link_to "Show", food, class:"m-2 btn btn-primary" %></li>
      |
      <li><%= button_to "Delete", food, method: :delete,class: "m-2 btn btn-danger" %></li>
    </ul>
  </td>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control m-2 w-50" %>
  </div>
  <div>
    <%= form.label :measurement_unit, style: "display: block", class: "form-label" %>
    <%= form.text_field :measurement_unit, class: "form-control m-2 w-50"  %>
  </div>
  <div>
    <%= form.label :price, style: "display: block", class: "form-label" %>
    <%= form.text_field :price, class: "form-control m-2 w-50"  %>
  </div>
  <div>
    <%= form.label :quantity, style: "display: block", class: "form-label" %>
    <%= form.number_field :quantity, class: "form-control m-2 w-50"  %>
  </div>
  <div>
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/foods/_shopping_item.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= recipe_food.process_quantity(food) %> <%= food.measurement_unit %></td>
  <td><%= number_to_currency(recipe_food.process_cost(food)) %></td>
</tr>

app/views/foods/edit.html.erb
<h1>Editing food</h1>
<%= render "form", food: @food %>
<br>
<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/general_shopping_list.html.erb
<h1>Shopping List</h1>

<div>
  <div>Amount of items to buy: <%= @items_to_buy %></div>
  <div>Total value of food needed: <%= @total_value %></div>
</div>

<%= render 'shared/shopping_table' do %>
  <% @foods.each do |food| %>
    <% recipe_food = RecipeFood.find_by(food:) %>
    <% unless recipe_food.nil? %>
      <%= render 'shopping_item', food:, recipe_food: %>
    <% end %>
  <% end %>
<% end %>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @food %>
<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food, url: recipe_recipe_foods_path(recipe), method: :post) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>
      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :food_id, style: "display: block", class: "form-label" %>
    <%= form.select :food_id, @foods.map {|food| ["#{food.name} in #{food.measurement_unit}", food.id]}, {}, { class: 'form-select form-select-lg' } %>
    If food not present you may <%= link_to 'Add New Food', action: :add_food %>
  </div>
  <div class="mb-3">
    <%= form.label :quantity, style: "display: block", class: "form-label" %>
    <%= form.number_field :quantity,  class: "form-control m-2 w-50"%>
  </div>
  <div>
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.food.measurement_unit %></td>
  <td>$<%= recipe_food.food.price %></td>
  <td><%= recipe_food.quantity %></td>
  <td class="d-flex justify-content-evenly">
    <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_food.recipe, recipe_food), class: "btn btn-primary" %>
    <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe, recipe_food), method: :delete, class: "btn btn-danger" %></td>
</tr>

app/views/recipe_foods/_shopping_item.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= recipe_food.quantity_needed %> <%= recipe_food.food.measurement_unit %></td>
  <td>$<%= recipe_food.cost_required %></td>
</tr>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Show this recipe food", recipe_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_path(@recipe_food.recipe) %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>

<%= render "form", recipe_food: @recipe_food, recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipe foods", recipe_recipe_foods_path(@recipe) %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_recipe_food_path(@recipe_food.recipe, @recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_recipe_foods_path(@recipe_food.recipe) %>

  <%= button_to "Destroy this recipe food", url: recipe_recipe_food_url(@recipe_food.recipe, @recipe_food), method: :delete %>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block", class: "form-label"  %>
    <%= form.text_field :name, class: "form-control m-2 w-50" %>
  </div>
  <div>
    <%= form.label :preparation_time, style: "display: block", class: "form-label"  %>
    <%= form.time_field :preparation_time, class: "form-control m-2 w-25" %>
  </div>
  <div>
    <%= form.label :cooking_time, style: "display: block", class: "form-label"  %>
    <%= form.time_field :cooking_time, class: "form-control m-2 w-25" %>
  </div>
  <div>
    <%= form.label :description, style: "display: block", class: "form-label"  %>
    <%= form.text_area :description, class: "form-control m-2 w-50 row-5" %>
  </div>
  <div class="form-check form-switch">
    <%= form.check_box :public, class: "form-check-input", role: "switch" %>
    <%= form.label :public, style: "display: block", class: "form-check-label"  %>
  </div>
  <div class="mt-4 actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/recipes/_listed_recipe.html.erb
<div class="container-lg row p-4 border border-secondary rounded shadow">
  <div class="col-3">
    <h3>
      <%= link_to recipe.name, recipe %>
    </h3>
    <% if can? :destroy, recipe %>
    <div><%= link_to 'Remove',
      recipe_path(recipe), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    },
      class: "btn btn-danger" %></div>
      <% end %>
  </div>
  <div class="col-5 text-truncate">
    <%= recipe.description %>
  </div>
</div>

app/views/recipes/_public_recipe.html.erb
<div class="container-lg row p-4 border border-secondary rounded shadow">
  <div class="col-3">
    <h3><%= link_to recipe.name, recipe %></h3>
    <h4><%= "By #{recipe.user.name}" %></h4>
    <% if can? :destroy, recipe %>
      <%= link_to 'Remove',
        recipe_path(recipe), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      },
        class: "btn btn-danger" %>
    <% end %>
  </div>
  <div class="d-flex flex-column col-5 gap-2 align-items-center">
    <div class="fs-4">Total food items: <%= recipe.recipe_foods.count %></div>
    <div class="fs-4">Total Price: <%= number_to_currency(recipe.total_cost) %></div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="d-flex flex-column gap-3">
  <h1 class="text-center">
    <%= recipe.name %>
  </h1>

  <div class="container-lg row">

    <div class="col">
      <div>
        <strong>Preparation time:</strong>
        <%= recipe.preparation_time.to_s(:time) %>
      </div>

      <div>
        <strong>Cooking time:</strong>
        <%= recipe.cooking_time.to_s(:time) %>
      </div>
    </div>
    
    <div class="col d-flex justify-content-end">
      <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDisabled" <%= 'checked' if recipe.public %> disabled>
        <label class="form-check-label" for="flexSwitchCheckDisabled">Public</label>
      </div>
    </div>
  </div>

  <div class="container-lg row">
    <h4>Description:</h4>
    <div><%= recipe.description %><div>
  </div>

  <div class="d-flex justify-content-between container-lg mt-3 mb-3">
    <%= link_to 'Generate Shopping List', recipe_shopping_list_path(recipe), class: 'btn btn-secondary' %>
    <%= link_to 'Add ingredient', new_recipe_recipe_food_path(recipe), class: 'btn btn-success' %>
  </div>
  <%= render 'shared/food_table' do %>
    <%= render @recipe_foods %>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public_recipes.html.erb
<p style="color: green"><%= notice %></p>

<h1>Public Recipes</h1>

<div id="recipes" class="d-flex flex-column align-items-center gap-3">
  <div class="container-lg align-self-start">
    <% if user_signed_in? %>
      <%= link_to 'Create new recipe', new_recipe_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
  <% if @recipes.count > 0 %>
    <% @recipes.each do |recipe| %>
      <%= render 'public_recipe', recipe: %>
    <% end %>
  <% else %>
    <h3>No public recipes posted</h3>
  <% end %>
</div>

app/views/recipes/shopping_list.html.erb
<h1>Shopping List</h1>

<div>
  <div>Amount of items to buy: <%= @items_to_buy %></div>
  <div>Total value of food needed: <%= @total_value %></div>
</div>

<%= render 'shared/shopping_table' do %>
  <% @recipe_foods.each do |recipe_food| %>
    <%= render 'recipe_foods/shopping_item', recipe_food: %>
  <% end %>
<% end %>

app/views/shared/_food_table.html.erb
<div class="container-fluid">
  <table class="table table-primary table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <%= yield %>
    </tbody>
  </table>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to 'Recipe App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Foods', foods_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Recipes', recipes_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'General Shopping List', general_shopping_list_path, class: "nav-link"%>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link"%>
        </li>
        
      </ul>
      <ul>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %>
            <li class="nav-item">Logged in as <strong><%= current_user.email %></strong>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'%></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, class: 'navbar-link' %>  |
              <%= link_to "Sign in", new_user_session_path, class: 'navbar-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_shopping_table.html.erb
<div class="container-fluid">
  <table class="table table-primary table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <%= yield %>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block", class: "form-label"  %>
    <%= form.text_field :name, class: "form-control m-2 w-50" %>
  </div>
  <div>
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>
<%= render "form", user: @user %>
<br>
<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p class="app-description">The Recipe app keeps track of all your recipes, ingredients, and inventory. It will 
allow you to save ingredients, keep track of what you have, create recipes, and generate 
a shopping list based on what you have and what you are missing from a recipe. 
Also, since sharing recipes is an important part of cooking the app should allow you 
to make them public so anyone can access them. </p>

app/views/users/new.html.erb
<h1>New user</h1>
<%= render "form", user: @user %>
<br>
<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @user %>
<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
  <%= button_to "Destroy this user", @user, method: :delete, class: "btn btn-danger" %>
</div>